//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by UnifyUI_FacTestTool.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_UNIFYUI_FACTESTTOOL_DIALOG  102
#define IDD_POPUP_DIALOG                103
#define IDR_MAINFRAME                   128
#define IDD_DOWNLOAD_STATION            129
#define IDD_IMEI_FC_STATION             130
#define IDD_OTHER_STATION               131
#define IDD_DIALOG_INIT                 132
#define IDD_DIALOG_RESULT               134
#define IDD_PASSWORD                    135
#define IDD_DIALOG1                     136
#define IDD_OTHERS_MULTI_STATION        136
#define IDD_POPUP_IMG_DIALOG            137
#define IDD_DIALOG2                     138
#define IDC_EDIT_Model                  1000
#define IDC_EDIT_Line                   1001
#define IDC_EDIT_PCBA                   1002
#define IDC_EDIT_SO                     1003
#define IDC_EDIT_PN                     1004
#define IDC_EDIT_ToolVer                1005
#define IDC_EDIT_Employee               1006
#define IDC_EDIT_UserLoadVer            1007
#define IDC_EDIT_FactoryVer             1008
#define IDC_TAB_StationPage             1009
#define IDC_EDIT_Total                  1010
#define IDC_EDIT_PASS                   1011
#define IDC_EDIT_FAIL                   1012
#define IDC_EDIT_Time                   1013
#define IDC_BUTTON_GO                   1014
#define IDC_BUTTON_Stop                 1015
#define IDC_BUTTON_EXIT                 1016
#define IDC_STATIC_TITLE                1017
#define IDC_STATIC_ID                   1018
#define IDC_STATIC_Model                1019
#define IDC_STATIC_Line                 1020
#define IDC_STATIC_PCBA                 1021
#define IDC_STATIC_SO                   1022
#define IDC_STATIC_PN                   1023
#define IDC_STATIC_ToolVer              1024
#define IDC_STATIC_Employee             1025
#define IDC_STATIC_FactoryVer           1026
#define IDC_STATIC_UserLoadVer          1027
#define IDC_STATIC_Record               1028
#define IDC_STATIC_Total                1029
#define IDC_STATIC_PASS                 1030
#define IDC_STATIC_FAIL                 1031
#define IDC_STATIC_Time                 1032
#define IDC_STATIC_Execute              1033
#define IDC_DL_STATIC_COM1              1034
#define IDC_DL_STATIC_COM2              1035
#define IDC_DL_STATIC_COM3              1036
#define IDC_DL_STATIC_COM4              1037
#define IDC_DL_STATIC_COM5              1038
#define IDC_DL_STATIC_COM6              1039
#define IDC_DL_STATIC_COM7              1040
#define IDC_DL_STATIC_COM8              1041
#define IDC_DL_STATIC_PERCENT1          1042
#define IDC_DL_STATIC_PERCENT2          1043
#define IDC_DL_STATIC_PERCENT3          1044
#define IDC_DL_STATIC_PERCENT4          1045
#define IDC_DL_STATIC_PERCENT5          1046
#define IDC_DL_STATIC_PERCENT6          1047
#define IDC_DL_STATIC_PERCENT7          1048
#define IDC_DL_STATIC_PERCENT8          1049
#define IDC_DL_PROGRESS_SUB1            1050
#define IDC_DL_PROGRESS_SUB2            1051
#define IDC_DL_PROGRESS_SUB3            1052
#define IDC_DL_PROGRESS_SUB4            1053
#define IDC_DL_PROGRESS_SUB5            1054
#define IDC_DL_PROGRESS_SUB6            1055
#define IDC_DL_PROGRESS_SUB7            1056
#define IDC_DL_PROGRESS_SUB8            1057
#define IDC_DL_PROGRESS_MAIN1           1058
#define IDC_DL_PROGRESS_MAIN2           1059
#define IDC_DL_PROGRESS_MAIN3           1060
#define IDC_DL_PROGRESS_MAIN4           1061
#define IDC_DL_PROGRESS_MAIN5           1062
#define IDC_DL_PROGRESS_MAIN6           1063
#define IDC_DL_PROGRESS_MAIN7           1064
#define IDC_DL_PROGRESS_MAIN8           1065
#define IDC_DL_EDIT_PICASSO1            1066
#define IDC_DL_EDIT_PICASSO2            1067
#define IDC_DL_EDIT_PICASSO3            1068
#define IDC_DL_EDIT_PICASSO4            1069
#define IDC_DL_EDIT_PICASSO5            1070
#define IDC_DL_EDIT_PICASSO6            1071
#define IDC_DL_EDIT_PICASSO7            1072
#define IDC_DL_EDIT_PICASSO8            1073
#define IDC_DL_LIST_SWPATH              1074
#define IDC_DL_STATIC_SWPATH            1075
#define IDC_DL_LIST_MESSAGE             1076
#define IDC_IMEI_STATIC_INFO            1077
#define IDC_IMEI_STATIC_TESTITEM        1078
#define IDC_IMEI_STATIC_ID              1079
#define IDC_LIST_IMEI_INFO              1080
#define IDC_LIST_IMEI_TESTITEM          1081
#define IDC_LIST_IMEI_MESSAGE           1082
#define IDC_EDIT_IMEI_ID                1083
#define IDC_RF_STATIC_TESTITEM          1084
#define IDC_IMEI_STATIC_NAL             1084
#define IDC_RF_STATIC_ID                1085
#define IDC_EDIT_IMEI_NAL               1085
#define IDC_LIST_RF_TESTITEM            1086
#define IDC_EDIT_RF_ID                  1087
#define IDC_LIST_RF_MESSAGE             1088
#define IDC_STATIC_PICTURE              1089
#define IDC_INIT_STATIC_Model           1090
#define IDC_RF_STATIC_PRESCAN           1090
#define IDC_STATIC_PRESCAN              1090
#define IDC_INIT_STATIC_PartNumber      1091
#define IDC_STATIC_TAG                  1091
#define IDC_INIT_STATIC_LoadVer         1092
#define IDC_INIT_STATIC_Station         1093
#define IDC_INIT_EDIT_Model             1094
#define IDC_INIT_EDIT_PartNumber        1095
#define IDC_INIT_EDIT_LoadVer           1096
#define IDC_INIT_COMBO_Station          1097
#define IDC_INIT_BUTTON_OK              1098
#define IDC_INIT_BUTTON_CANCEL          1099
#define IDC_RESULT_STATIC_CAPTION       1100
#define IDC_INIT_EDIT_LoadVer2          1100
#define IDC_INIT_EDIT_EMPLOYEEID        1100
#define IDC_RESULT_STATIC_MSG           1101
#define IDC_INIT_STATIC_EMPLOYEE        1101
#define IDC_EDIT_PASSWORD               1102
#define IDC_EDIT_PRESCAN                1105
#define IDC_BUTTON_NEXT                 1106
#define IDC_EDIT_TAG                    1107
#define IDC_STATIC_TEXT                 1108
#define IDC_STATIC_ERROR                1109
#define IDC_STATIC_VER                  1111
#define IDC_STATIC_SHOW_IMG             1112
#define IDC_STATIC_Acer22               1113
#define IDC_EDIT_IMEI_Acer22            1114
#define IDC_BUTTON1                     1115
#define IDC_BUTTON_CYCLETEST            1115
#define IDC_LIST_TESTITEM2              1139
#define IDC_EDIT_RF_ID2                 1140
#define IDC_LIST_TESTITEM3              1141
#define IDC_LIST_TESTITEM4              1142
#define IDC_EDIT_RF_ID3                 1144
#define IDC_EDIT_RF_ID4                 1145
#define IDC_STATIC1                     1149
#define IDC_STATIC2                     1150
#define IDC_STATIC3                     1151
#define IDC_STATIC4                     1152

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        139
#define _APS_NEXT_COMMAND_VALUE         32771
#define _APS_NEXT_CONTROL_VALUE         1116
#define _APS_NEXT_SYMED_VALUE           106
#endif
#endif
