#ifndef _DLERROR_H_
#define _DLERROR_H_

// device error
#define DLERR_TARGET_ERROR				"DL1000"
#define DLERR_BOOTROM_ERROR				"DL1001"
#define DLERR_TIMEOUT					"DL1002"
#define DLERR_MOBILEID_ERROR			"DL1003"
#define DLERR_FACTORY_AREA_NOT_ACTIVE	"DL1004"
#define DLERR_PHONE_IN_DL_MODE			"DL1005"
#define DLERR_WRITE_FACTORY_AREA_FAIL	"DL1006"
#define DLERR_NO_HANDSET				"DL1007"
#define DLERR_SIGNED_FAIL				"DL1008"
#define DLERR_SWVERSION_FAIL			"DL1009"
#define DLERR_HWVERSION_FAIL			"DL1010"
#define DLERR_MEVERSION_FAIL			"DL1011"
#define DLERR_CLOSE_CONNECTION_FAIL		"DL1012"
#define DLERR_RESET_INCOMPLETE			"DL1013"
#define DLERR_EXE_COMMAND_FAIL			"DL1014"
#define DLERR_WRITE_MOBILEID_FAIL		"DL1015"
#define DLERR_WRITE_PICASSO_FAIL		"DL1016"
#define DLERR_WRITE_VERSIONINFO_FAIL	"DL1017"

// download error
#define DLERR_PARTITION_TABLE_DIFFER	"DL2000"
#define DLERR_PARTITION_ERASE_FAIL		"DL2001"
#define DLERR_DL_PARTITION_FAIL			"DL2002"
#define DLERR_DL_DBL_FAIL				"DL2003"
#define DLERR_DL_FSBL_FAIL				"DL2004"
#define DLERR_DL_OSBL_FAIL				"DL2005"
#define DLERR_DL_AMSS_FAIL				"DL2006"
#define DLERR_DL_DSP1_FAIL				"DL2007"
#define DLERR_DL_DT_FAIL				"DL2008"
#define DLERR_DL_RESERVED_FAIL			"DL2009"
#define DLERR_DATA_CHECKSUM_ERROR		"DL2010"
#define DLERR_RS232_DL_ERROR			"DL2011"
#define DLERR_DL_DEFAULT_QCN_FAIL		"DL2012"
#define DLERR_BACKUPNV_FAIL				"DL2013"
#define DLERR_DL_MAINCODE_CEFS_FAIL		"DL2014"
#define DLERR_RESTORENV_FAIL			"DL2015"
#define DLERR_LOADIMAGE_FAIL			"DL2016"
#define DLERR_CHECKNV_PARTITION_ERROR	"DL2017"

// logs error
#define DLERR_WRITE_PICS_FAIL			"DL3000"

// other
#define DLERR_WRITE_QFUSE_FAIL			"DL4000"
#define DLERR_READ_QFUSE_FAIL			"DL4001"
#define DLERR_QUERY_ISSPCLOCKED_FAIL	"DL4002"
#define DLERR_UNLOCKSPC_FAIL			"DL4003"
#define DLERR_READ_IMEI_FAIL			"DL4004"
#define DLERR_IMEISTATUS_NOT_B_R_D		"DL4005"
#define DLERR_BACKUPBRT_FAIL			"DL4006"
#define DLERR_CHECKPROCESS_FAIL			"DL4007"


#define DLERR_UNKNOWN					"DL9999"



#endif //_DLERROR_H_


