/***************************************************************************
*
/* T-Line */
#define STATION_MULTIFT			      _T("MULTIFT")
#define STATION_DL					  _T("DL")
#define STATION_TRIGGER			      _T("TRIGGER")
#define STATION_BOOT				  _T("BOOT")
#define STATION_2GPTEST			      _T("2GPTEST")
#define STATION_3GPTEST			      _T("3GPTEST")
#define STATION_4GPTEST			      _T("4GPTEST")
#define STATION_BBTEST 			      _T("BBTEST")
#define STATION_BTWLAN 			      _T("BTWLAN")
#define STATION_2G3GTEST              _T("2G3GTEST")
#define STATION_REDL				  _T("Re-DL")
#define STATION_LTE     		      _T("LTE")

/* A-Line */
#define STATION_ONLINE_WLS		      _T("ONLINE_WLS")
#define STATION_ONLINE_WLS2		      _T("ONLINE_WLS2")
#define STATION_ONLINE_WLS3		      _T("ONLINE_WLS3")
#define STATION_MMI_BB			      _T("MMI_BB")
#define STATION_ALS_AUDIO			  _T("ALS_AUDIO")
#define STATION_TOUCH				  _T("TOUCH")
#define STATION_CAMERA				  _T("CAMERA")
#define STATION_CAMERA_1              _T("CAMERA1")
#define STATION_CAMERA_2              _T("CAMERA2")
#define STATION_MMI_EM			      _T("MMI_EM")
#define STATION_FALINK			      _T("FALINK")
#define STATION_VI				      _T("VI")
#define STATION_RUN_IN				  _T("RUN_IN")
#define STATION_CSDEM		          _T("CSDEM")
#define STATION_CSDWIFI_0	          _T("CSDWIFI_0")
#define STATION_CSDWIFI_1	          _T("CSDWIFI_1")
#define STATION_CSDWRITE	          _T("CSDWRITE")
#define STATION_CSDWRITE_SN	          _T("CSDWRITE_SN")
#define STATION_CSDREAD_SN          _T("CSDREAD_SN")

/* P-Line */
#define STATION_IMEI			      _T("IMEI")
#define STATION_OS_DL			      _T("OS_DL")
#define STATION_FCHECK			      _T("FCHECK")
#define STATION_PPIDLINK		      _T("PPIDLINK")
#define STATION_GB_PRINTING		      _T("GB_PRINTING")
#define STATION_FFU				      _T("FFU")
#define STATION_MMI_TEST			  _T("MMI_TEST")
#define STATION_ALS					  _T("ALS")
#define STATION_AUDIO				  _T("AUDIO")
#define STATION_CURRENT				  _T("CURRENT")
#define STATION_NAL_SCAN              _T("NAL_SCAN")
#define STATION_PREMMIBB			  _T("PRE_MMI")
#define STATION_CSDPREMMIBB			  _T("CSD_PRE_MMI")

/* OOB */
#define STATION_OOB				      _T("OOB")
