#ifndef _COMM_ERRORDEFINE_H
#define _COMM_ERRORDEFINE_H

#define CommErr_PASS                                         "PASS"
//**Software Version
#define CommErr_Get_Software_Version_Fail                    "Get_Software_Version_Fail"
#define CommErr_Check_Software_Version_Fail                  "Check_Software_Version_Fail"
#define CommErr_Check_BIST_Version_Fail                      "Check_BIST_Version_Fail"
//Hardware Version
#define CommErr_Get_Hardware_Version_Fail                    "Get_Hardware_Version_Fail"
#define CommErr_Check_Hardware_Version_Fail                  "Check_Hardware_Version_Fail"
#define CommErr_Get_Mechaical_Version_Fail                   "Get_Mechaical_Version_Fail"
#define CommErr_Check_Mechaical_Version_Fail                 "Check_Mechaical_Version_Fail"
//HW ID
#define CommErr_Get_HW_ID_Fail                               "Get_HW_ID_Fail"
#define CommErr_Check_HW_ID_Fail                             "Check_HW_ID_Fail"
#define CommErr_Check_HW_ID_Rule_Fail                        "Check_HW_ID_Rule_Fail"
//**Read and Write FA
#define CommErr_Factory_Area_Not_Active                      "Factory_Area_Not_Active"
#define CommErr_Read_Factory_Area_Fail                       "Read_Factory_Area_Fail"
#define CommErr_Write_Factory_Area_Fail                      "Write_Factory_Area_Fail"
//**OTP
#define CommErr_Query_OTP_Status_Fail                        "Query_OTP_Status_Fail"
#define CommErr_Freeze_OTP_Fail                              "Freeze_OTP_Fail"
#define CommErr_OTP_Damaged_Or_Warning                       "OTP_Damaged_Or_Warning"
//**SPC
#define CommErr_Read_SPC_Code_Fail                           "Read_SPC_Code_Fail"
#define CommErr_Write_SPC_Code_Fail                          "Write_SPC_Code_Fail"
#define CommErr_SPC_Code_Error                               "SPC_Code_Error"
#define CommErr_SPC_Unlock_Fail                              "SPC_Unlock_Fail"
#define CommErr_SPC_lock_Fail                                "SPC_lock_Fail"
#define CommErr_Query_SPC_lock_Status_Fail                   "Query_SPC_lock_Status_Fail"
#define CommErr_Compare_SPC_Code_Fail                        "Compare_SPC_Code_Fail"
//**Partition
#define CommErr_Clear_All_Item_Fail                          "Clear_All_Item_Fail"
#define CommErr_Unlock_Partition_Fail                        "Unlock_Partition_Fail"
//**Sim data
#define CommErr_Encode_Sim_Data_Fail                         "Encode_Sim_Data_Fail"
#define CommErr_Write_Sim_Data_Fail                          "Write_Sim_Data_Fail"
#define CommErr_Check_Sim_Data_Fail                          "Check_Sim_Data_Fail"
#define CommErr_Write_Public_key_Fail                        "Write_Public_key_Fail"
#define CommErr_Read_Public_key_Fail                         "Read_Public_key_Fail"
#define CommErr_Compare_Public_key_Fail                      "Compare_Public_key_Fail"
#define CommErr_SimLock_GetControlKey_Fail                   "SimLock_GetControlKey_Fail"
#define CommErr_Unlock_Phone_Code_Fail                       "Unlock_Phone_Code_Fail"
#define CommErr_Read_Sim_Data_Fail                           "Read_Sim_Data_Fail"
#define CommErr_Activate_SimLock_Fail                        "Activate_SimLock_Fail"
#define CommErr_Deactivate_SimLock_Fail                      "Deactivate_SimLock_Fail"
//**PVK
#define CommErr_Write_PVK_File_Fail                          "Write_PVK_File_Fail"
#define CommErr_Load_PVK_File_Fail                           "Load_PVK_File_Fail"
#define CommErr_Check_PVK_Status_Fail                        "Check_PVK_Status_Fail"
#define CommErr_Decrypt_PVK_Fail                             "Decrypt_PVK_Fail"
#define CommErr_No_PVK_File_Found                            "No_PVK_File_Found"
//**phone
#define CommErr_No_Phone_Connected                           "No_Phone_Connected"
#define CommErr_Connect_Phone_Fail_After_Sim_Data            "Connect_Phone_Fail_After_Sim_Data"
#define CommErr_Connect_Phone_Fail_After_PVK_Reset           "Connect_Phone_Fail_After_PVK_Reset"
#define CommErr_Close_Phone_Connection_Fail                  "Close_Phone_Connection_Fail"
#define CommErr_Reset_Phone_Fail                             "Reset_Phone_Fail"
#define CommErr_Get_ADB_Fail                                 "Get_ADB_Fail"
#define CommErr_Set_Phone_To_Ftd_Mode_Fail                   "Set_Phone_To_Ftd_Mode_Fail"
#define CommErr_Set_Phone_To_Online_Mode_Fail                "Set_Phone_To_Online_Mode_Fail"
#define CommErr_Phone_Not_FTD                                "Phone_Not_In_FTD_Mode"
#define CommErr_Phone_Restart_Fail                           "Phone_Restart_Fail"
#define CommErr_Phone_Modem_Not_Ready_Fail                   "Phone_Modem_Not_Ready_Fail"
#define CommErr_Set_Phone_To_FTM_Mode_Fail                   "Set_Phone_To_FTM_Mode_Fail"
#define CommErr_Reopen_Comport_Fail                          "Reopen_Comport_Fail"
#define CommErr_Device_In_eDL_Mode                           "Device_In_eDL_Mode"
#define CommErr_Device_In_Fastboot_Mode                      "Device_In_Fastboot_Mode"
//**File
#define CommErr_Pull_File_From_Device_Fail                   "Pull_File_From_Device_Fail"
#define CommErr_Push_File_To_Device_Fail                     "Push_File_To_Device_Fail"
#define CommErr_Parse_File_Fail                              "Parse_File_Fail"
//**NV & EFS
#define CommErr_Backup_NV_Fail                               "Backup_NV_Fail"
#define CommErr_Restore_NV_Fail                              "Restore_NV_Fail"
#define CommErr_Check_NV_Backup_Fail                         "Check_NV_Backup_Fail"
#define CommErr_Read_NV_Fail                                 "Read_NV_Fail"
#define CommErr_Write_NV_Fail                                "Write_NV_Fail"
#define CommErr_EFS_Sync_Fail                                "EFS_Sync_Fail"
#define CommErr_Write_Init_NV_Fail                           "Write_InitNV_Fail"
#define CommErr_Load_NV_Definition_File_Fail                 "Load_NV_Definition_File_Fail"
//**Factroy Reset
#define CommErr_Master_Clear_Fail                            "Master_Clear_Fail"
//**Qfuse
#define CommErr_Write_Qfuse_Fail                             "Write_Qfuse_Fail"
#define CommErr_Read_Qfuse_Fail                              "Read_Qfuse_Fail"
#define CommErr_Check_Qfuse_Fail                             "Check_Qfuse_Fail"
//**XML related
#define CommErr_XML_Testitem_Load_Fail                       "XML_Testitem_Load"
#define CommErr_XML_Cableloss_Load_Fail                      "XML_Cableloss_Load"
#define CommErr_XML_Deviceitem_Load_Fail                     "XML_Deviceitem_Load"
#define CommErr_XML_Testitem_Parameter_Missed                "XML_Testitem_Parameter"
#define CommErr_XML_Cableloss_Parameter_Missed               "XML_Cableloss_Parameter"
#define CommErr_XML_Deviceitem_Parameter_Missed              "XML_Deviceitem_Parameter"
#define CommErr_XML_GoldenSample_Load_Fail                   "XML_GoldenSample_Load"
//**Golden
#define CommErr_Is_Golden_Sample                             "Is_Golden_Sample"
#define CommErr_Is_Not_Golden_Sample                         "Is_Not_Golden_Sample"
//**PPID
#define CommErr_Check_PPID_Length_Fail                       "PPID_Length_Fail"
#define CommErr_Check_PPID_Rule_Fail                         "PPID_Rule_Fail"
#define CommErr_Write_PPID_Fail                              "PPID_Write_Fail"
#define CommErr_Read_PPID_Fail                               "PPID_Read_Fail"
#define CommErr_Check_PPID_Fail                              "PPID_Check_Fail"
//**FSN
#define CommErr_FSN_Length_Fail                              "FSN_Size_Fail"
#define CommErr_Compare_MSN_Fail                             "Compare_FSN_Fail"
#define CommErr_Read_FSN_Fail                                "Read_FSN_Fail"
#define CommErr_Write_FSN_Fail                               "Write_FSN_Fail"
#define CommErr_No_FSN_Record_in_DB                          "NO_FSN_Record_IN_DB"
//**BT Address
#define CommErr_Read_BT_Address_Fail                         "Read_BT_Address_Fail"
#define CommErr_Write_BT_Address_Fail                        "Write_BT_Address_Fail"
#define CommErr_Compare_BT_Address_Fail                      "Compare_BT_Address_Fail"
#define CommErr_Check_BT_Address_Length_Fail                 "Check_BT_Address_Length_Fail"
//**WLAN Address
#define CommErr_Check_WLAN_Address_Length_Fail               "Check_WLAN_Address_Length_Fail"
#define CommErr_Read_WLAN_Address_Fail                       "Read_WLAN_Address_Fail"
#define CommErr_Write_WLAN_Address_Fail                      "Write_WLAN_Address_Fail"
#define CommErr_Compare_WLAN_Address_Fail                    "Compare_WLAN_Address_Fail"
//**IMEI
#define CommErr_Check_IMEI_Rule_Fail                         "Check_IMEI_Rule_Fail"
#define CommErr_Check_IMEI_Fail_In_Rework                    "Check_IMEI_Fail_In_Rework"
#define CommErr_IMEI_Default_In_Phone_Error                  "IMEI_Default_In_Phone_Error"
#define CommErr_No_IMEI_In_Phone_When_rework                 "No_IMEI_In_Phone_When_rework"
#define CommErr_IMEI_Status_In_P_S_Error                     "IMEI_Status_In_P_S_Error"
#define CommErr_IMEI_Status_Error                            "IMEI_Status_Error"
#define CommErr_Check_IMEI_Sequence_Fail                     "Check_IMEI_Sequence_Fail"
#define CommErr_Read_IMEI_Fail                               "Read_IMEI_Fail"
#define CommErr_Write_IMEI_Fail                              "Write_IMEI_Fail"
#define CommErr_Compare_IMEI_Fail                            "Compare_IMEI_Fail"
#define CommErr_Print_IMEI_Label_Fail                        "Print_IMEI_Label_Fail"
//**MEID
#define CommErr_Check_MEID_Length_Fail                       "Check_MEID_Length_Fail"
#define CommErr_Read_MEID_Fail                               "Read_MEID_Fail"
#define CommErr_Write_MEID_Fail                              "Write_MEID_Fail"
#define CommErr_Compare_MEID_Fail                            "Compare_MEID_Fail"
//**SSSO2
#define CommErr_Initial_SSSO2_Fail                           "Initial_PICS_SSS02_Fail"
#define CommErr_Query_BT_WLAN_MSN_From_SSS_Fail              "Query_BT_WLAN_MSN_From_SSS_Fail"
#define CommErr_Query_IMEI_Status_From_PICS_Fail             "Query_IMEI_Status_From_PICS_Fail"
#define CommErr_Query_SPC_Code_From_PICS_Fail                "Query_SPC_Code_From_PICS_Fail"
#define CommErr_Query_FSN_From_PICS_Fail                     "Query_FSN_From_PICS_Fail"
#define CommErr_Create_FSN_From_PICS_Fail                    "Created_FSN_From_PICS_Fail"
#define CommErr_Query_Unlock_key_From_PICS_Fail              "Query_Unlock_key_From_PICS_Fail"
#define CommErr_Query_Sim_Data_From_PICS_Fail                "Query_Sim_Data_From_PICS_Fail"
#define CommErr_Get_Sim_Data_Size_From_PICS_Fail             "Get_Sim_Data_Size_From_PICS_Fail"
#define CommErr_Update_IMEI_Status_To_PICS_Fail              "Update_IMEI_Status_To_PICS_Fail"
#define CommErr_Check_IMEI_PN_MAL_In_PICS_Fail               "Check_IMEI_PN_MAL_In_PICS_Fail"
#define CommErr_Create_IMEI_Table_In_PICS_Fail               "Create_IMEI_Table_In_PICS_Fail"
#define CommErr_Update_NAL_To_PICS_Fail                      "Update_NAL_To_PICS_Fail"
#define CommErr_Update_CustomerSW_To_SSSO2_Fail              "Update_CustomerSW_To_SSSO2_Fail"
#define CommErr_Query_MEID_From_SSS_Fail                     "Query_MEID_From_SSS_Fail"
#define CommErr_Check_CustomerPN_From_SSSO2_Fail             "Check_CustomerPN_From_SSSO2_Fail"
#define CommErr_Get_SPC_PICS_Fail                            "Get_SPC_PICS_Fail"
//**Serial Number
#define CommErr_Read_Serial_Number_Fail                      "Read_Serial_Number_Fail"
#define CommErr_Write_Serial_Number_Fail                     "Write_Serial_Number_Fail"
#define CommErr_Compare_Serial_Number_Fail                   "Compare_Serial_Number_Fail"
//**NAL
#define CommErr_Check_NAL_Rule_Fail                          "Check_NAL_Rule_Fail"
#define CommErr_NAL_NOT_IN_DB                                "NAL_NOT_IN_DB"
#define CommErr_NAL_Duplicated                               "NAL_DUPLICATED"
//**DRM
#define CommErr_Create_DRM_Fail                              "Create_DRM_Fail"
#define CommErr_DRM_Backup_Fail                              "DRM_Backup_Fail"
//**Device Control
#define CommErr_PowerSupply_Control_Fail                     "PowerSupply_Control_Fail"
#define CommErr_RelayBoard_Control_Fail                      "RelayBoard_Control_Fail"
#define CommErr_Jig_Move_Fail                                "Jig_Move_Fail"
#define CommErr_Detect_RF_Tester_Fail                        "Detect_RF_Tester_Fail"
#define CommErr_Check_RF_Tester_Option_Fail                  "Check_RF_Tester_Option_Fail"
#define CommErr_RF_Tester_Fail_Need_Restart                  "RF_Tester_Fail_Need_Restart"
#define CommErr_Assist_Device_Detect_Fail                    "Assist_Device_Detect_Fail"
//**RF relative
#define CommErr_Get_Channel_Type_Fail                        "Get_Channel_Type_Fail"
#define CommErr_No_Band_Define_Fail                          "No_Band_Define_Fail"
//**Flag
#define CommErr_Write_FC_Flag_Fail                           "Write_FC_Flag_Fail"
#define CommErr_Check_FC_Flag_Fail                           "Check_FC_Flag_Fail"
//**UI related
#define CommErr_UI_Unknown_Error_From_DLL                    "UI_Unknown_Error_From_DLL"
#define CommErr_UI_Init_Diag_Fail                            "UI_Init_Diag_Fail"
#define CommErr_UI_DLL_Load_Fail                             "UI_DLL_Load_Fail"
#define CommErr_UI_Config_File_Not_Found                     "UI_Config_File_Not_Found"
#define CommErr_UI_Config_File_Miss_Parameter                "UI_Config_File_Miss_Parameter"
#define CommErr_UI_Init_TestItem_Fail                        "UI_Init_TestItem_Fail"
//UI cim related
#define CommErr_UI_CIM_MobileID_Match_Fail                   "UI_CIM_MobileID_Match_Fail"
#define CommErr_UI_CIM_SO_CR_Count_Over_Upper                "UI_CIM_SO_CR_Count_Over_Upper"
#define CommErr_UI_CIM_SO_NULL                               "UI_CIM_SO_NULL"
#define CommErr_UI_CIM_SMT_Picasso_Not_Exist                 "UI_CIM_SMT_Picasso_Not_Exist"
#define CommErr_UI_CIM_Picasso_Locked                        "UI_CIM_Picasso_Locked"
#define CommErr_UI_CIM_Picasso_Status_Invalide               "UI_CIM_Picasso_Status_Invalide"
#define CommErr_UI_CIM_Picasso_Match_Phone_Fail              "UI_CIM_Picasso_Match_Phone_Fail"
#define CommErr_UI_CIM_Routing_Check_Fail                    "UI_CIM_Routing_Check_Fail"
#define CommErr_UI_CIM_Connect_Fail                          "UI_CIM_Connect_Fail"
#define CommErr_UI_CIM_Picasso_QA_Hold                       "UI_CIM_Picasso_QA_Hold"
#define CommErr_UI_CIM_Pics_Clean_Fail                       "UI_CIM_Pics_Clean_Fail"
#define CommErr_UI_CIM_Interface_Get_Fail                    "UI_CIM_Interface_Get_Fail"
#define CommErr_UI_CIM_Picasso_Match_IMEI_Fail               "UI_CIM_Picasso_Match_IMEI_Fail"
#define CommErr_UI_CIM_Tool_Version_Invalide                 "UI_CIM_Tool_Version_Invalide"
#define CommErr_UI_CIM_IMEI_Status_Invalide                  "UI_CIM_IMEI_Status_Invalide"
#define CommErr_UI_CIM_EmployeeID_Not_TS                     "UI_CIM_EmployeeID_Not_TS"
#define CommErr_UI_CIM_Phone_Init_Not_Record                 "UI_CIM_Phone_Init_Not_Record"
#define CommErr_UI_CIM_Phone_Reocrd_Not_Init                 "UI_CIM_Phone_Reocrd_Not_Init"
//UI pvcs related
#define CommErr_UI_PVCS_ParamList_Invalide                   "UI_PVCS_ParamList_Invalide"
#define CommErr_UI_PVCS_PN_Segment_Match_Fail                "UI_PVCS_PN_Segment_Match_Fail"
//UI input related
#define CommErr_UI_Picasso_Invalide                          "UI_Picasso_Invalide"
#define CommErr_UI_Picasso_Not_Input                         "UI_Picasso_Not_Input"
#define CommErr_UI_Picasso_Duplicated                        "UI_Picasso_Duplicated"
#define CommErr_UI_Picasso_Match_Phone_Fail                  "UI_Picasso_Match_Phone_Fail"
#define CommErr_UI_IMEI_Not_Input                            "UI_IMEI_Not_Input"
#define CommErr_UI_IMEI_Rule_Check_Fail                      "UI_IMEI_Rule_Check_Fail"
#define CommErr_UI_IMEI_First_Part_Fail                      "UI_IMEI_First_Part_Fail"
#define CommErr_UI_NAL_Not_Input                             "UI_NAL_Not_Input"
#define CommErr_UI_NAL_Rule_Check_Fail                       "UI_NAL_Rule_Check_Fail"
#define CommErr_UI_FA_Model_Invalide                         "UI_FA_Model_Invalide"
#define CommErr_UI_FA_SWVersion_Invalide                     "UI_FA_SWVersion_Invalide"
//UI DL page related
#define CommErr_UI_DL_Image_Not_Exist                        "UI_DL_Image_Not_Exist"
#define CommErr_UI_DL_Run_Thread_Fail                        "UI_DL_Run_Thread_Fail"
//UIinterface related
#define CommErr_UI_Interface_Prerun_Fail                     "UI_Interface_Prerun_Fail"
#define CommErr_UI_Interface_Setparameter_Fail               "UI_Interface_Setparameter_Fail"
#define CommErr_UI_Interface_Getparameter_Fail               "UI_Interface_Getparameter_Fail"
#define CommErr_UI_Interface_GetFA_Fail                      "UI_Interface_GetFA_Fail"
#define CommErr_UI_Interface_SetFA_Fail                      "UI_Interface_SetFA_Fail"
#define CommErr_UI_Interface_Begin_Fail                      "UI_Interface_Begin_Fail"
//UI power supply
#define CommErr_UI_PowerSupply_On_Fail                       "UI_PowerSupply_On_Fail"
#define CommErr_UI_PowerSupply_Off_Fail                      "UI_PowerSupply_Off_Fail"
#define CommErr_UI_PowerSupply_Detect_Fail                   "UI_PowerSupply_Detect_Fail"
//UI jig control
#define CommErr_UI_Jig_Open_Fail                             "UI_Jig_Open_Fail"
#define CommErr_UI_Jig_Close_Fail                            "UI_Jig_Close_Fail"
#define CommErr_UI_Jig_Com_Open_Fail                         "UI_Jig_Com_Open_Fail"
#define CommErr_UI_Jig_Data_Send_Fail                        "UI_Jig_Data_Send_Fail"
//UI relayboard
#define CommErr_UI_RelayBoard_Init_Fail                      "UI_RelayBoard_Init_Fail"
#define CommErr_UI_RelayBoard_Set_Fail                       "UI_RelayBoard_Set_Fail"
//UI batch command
#define CommErr_UI_Cmd_Fail                                  "UI_Cmd_Fail"
#define CommErr_UI_Cmd_Time_Syn_Fail                         "UI_Cmd_Time_Syn_Fail"
//**MD5
#define CommErr_MD5_Check_Fail								 "MD5_Check_Fail"
//**WVL1
#define CommErr_Write_WVL1_Key_Fail                          "Write_WVL1_Key_Fail"
#define CommErr_Read_WVL1_Key_Fail                           "Read_WVL1_Key_Fail"
#define CommErr_Remove_WVL1_Key_Fail                         "Remove_WVL1_Key_Fail"
#define CommErr_Compare_WVL1_Key_Fail                        "Compare_WVL1_Key_Fail"
//**HDCP
#define CommErr_Write_HDCP_Key_Fail                          "Write_HDCP_Key_Fail"
#define CommErr_Read_HDCP_Key_Fail                           "Read_HDCP_Key_Fail"
#define CommErr_Remove_HDCP_Key_Fail                         "Remove_HDCP_Key_Fail"
#define CommErr_Compare_HDCP_Key_Fail                        "Compare_HDCP_Key_Fail"
//**WifiCountryCode
#define CommErr_Write_WifiCountryCode_Fail                   "Write_WifiCountryCode_Fail"
#define CommErr_Read_WifiCountryCode_Fail                    "Read_WifiCountryCode_Fail"
#define CommErr_Compare_WifiCountryCode_Fail                 "Compare_WifiCountryCode_Fail" 
//**Factory time
#define CommErr_Write_Factory_Time_Fail                      "Write_Factory_Time_Fail"
#define CommErr_Read_Factory_Time_Fail                       "Read_Factory_Time_Fail"
//**others
#define CommErr_Load_DLL_Fail                                "Load_DLL_Fail"
#define CommErr_Install_APK_Fail                             "Install_APK_Fail"
//**Ethernet
#define CommErr_Read_Ethernet_Mac_Address_Fail               "Read_Ethernet_Mac_Address_Fail"
#define CommErr_Write_Ethernet_Mac_Address_Fail              "Write_Ethernet_Mac_Address_Fail"

#endif //_COMM_ERRORDEFINE_H
