{Header
}
{Description
Set BootMode to FTM Mode via QMSL API.
NOTICE: Probably make DUT get stuck on Offline mode.
}
{Parameter
}
{Code
0000 waitinput %var0 COMPort
0001 waitinput %var1 UseQPST
0002 Run CmdModuleExport.dll PhoneMode_QMSL_SetBootMode_SPU %var0 %var1 1 0 1 0
0003 comparetrue 0006
0004 print "Set BootMode FTM via QMSL FAILURE"
0005 comparefalse 9999
0006 print "Set BootMode FTM via QMSL SUCCESS"
}