{Header
}
{Description
Get Current Phone Mode via Diag CMD.
}
{Parameter
}
{Code
0000 waitinput %var0 COMPort
0001 waitinput %var1 UseQPST 

0002 Run CmdModuleExport.dll DiagCmd_SAMPLE_SPU %var0 %var1 1 0 %var2 %var3
0003 print %var2
0004 comparetrue 0008

0005 print %var3 "[ErrorMsg] "
0006 print "FAIL to execute DiagCmd_SAMPLE_SPU"
0007 comparefalse 9999

0008 print "SUCCESS to execute DiagCmd_SAMPLE_SPU"
}